Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,39 +1,100 @@
-name: New Workflow
+name: CI Build Workflow
 
-on:
-  push:
-    branches:
-      - main  
+on: [push]
 
 jobs:
-  build:
+  ci-build:
+    name: CI Build
     runs-on: ubuntu-latest
-
+    strategy:
+      fail-fast: false
+      matrix:
+        python-version: ["3.11.4"]
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+    - name: Checkout
+      uses: actions/checkout@v3
+    
+    - name: Set up Python ${{ matrix.python-version }}
+      uses: actions/setup-python@v3
+      with:
+        python-version: ${{ matrix.python-version }}
+        
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        echo "============================================="
+        echo "Installing requirements.txt...."
+        pip3 install -r requirements.txt
+        echo "============================================="
+        echo "Installing pylint...."
+        pip3 install pylint
+        
+    - name: Analysing the code with pylint
+      run: |
+        # Need to add true at the end as pylint will fail right now due to static code analysis findings
+        pylint $(git ls-files '*.py' | grep -v "dummy") || true
 
-      - name: Set up Python
-        uses: actions/setup-python@v2
+
+  run-tests:
+    name: Run Tests
+    runs-on: ubuntu-latest
+    needs: ci-build
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+
+    - name: Sleep and Run
+      run: |
+        echo "Sleeping for 3"
+        sleep 3
+  
+
+  docker-build:
+    name: Docker Build
+    runs-on: ubuntu-latest
+    needs: run-tests
+    if: github.ref == 'refs/heads/main'  # Run only on the main branch
+    strategy:
+      fail-fast: false
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      
+      - name: Docker meta tags generator
+        id: meta
+        uses: docker/metadata-action@v5
         with:
-          python-version: 3.11
+          # list of Docker images to use as base name for tags
+          images: |
+            poonamsabharwal/citadel-idp-frontend 
+          # TODO: need to add condition later about when to build the docker tag "latest". Dont want ot build it for every docker push
+          flavor: |
+            latest=true
+          # generate Docker tags
+          tags: |
+            type=raw,enable=true,value=sha-{{ sha }}_build-{{ date 'YYYYMMDD-HHmmss' tz='UTC' }}     
 
-      - name: Install pytest
-        run: pip install pytest
-
-      - name: Run pylint
-        run: |
-          pylint .
-        continue-on-error: true  
-
-      - name: Run tests
-        run: echo "No tests to run"   
-     
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+      
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
-
-      - name: Build and push Docker image
-        run: |
-          docker buildx create --use
-          docker buildx build --platform linux/amd64,linux/arm64 -t citadel:ftest .
-          docker push citadel:ftest
+        uses: docker/setup-buildx-action@v3
+        with:
+          buildkitd-flags: --debug
+      
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: poonamsabharwal
+          password: dckr_pat_J61TsbBzpwqA4zOGTvtuiuvRprg
+      
+      - name: Build and push
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          file: ./Dockerfile
+          push: true
+          platforms: linux/amd64,linux/arm64
+          tags: ${{ steps.meta.outputs.tags }}
+          # labels: ${{ steps.meta.outputs.labels }}
+    
